export const API_URL = import.meta.env.VITE_GRAPHQL_ENDPOINT;

export const SECTOR_MAP: Record<string, string> = {
  COMMUNICATIONS: '통신 서비스',
  CONSUMER_DISCRETIONARY: '임의소비재',
  CONSUMER_STAPLES: '필수소비재',
  ENERGY: '에너지',
  FINANCIALS: '금융',
  HEALTH_CARE: '헬스케어',
  INDUSTRIALS: '산업재',
  INFORMATION_TECHNOLOGY: '정보기술',
  MATERIALS: '소재',
  REAL_ESTATE: '부동산',
  UNCLASSIFIED: '미분류',
  UTILITIES: '유틸리티',
};

export const INDUSTRY_MAP: Record<string, string> = {
  MATERIALS: '소재',
  ENERGY: '에너지',
  CAPITAL_GOODS: '자본재',
  COMMERCIAL_PROFESSIONAL_SERVICES: '상업 및 전문 서비스',
  TRANSPORTATION: '운송',
  AUTOMOBILES_COMPONENTS: '자동차 및 부품',
  CONSUMER_DURABLES_APPAREL: '내구 소비재 및 의류',
  CONSUMER_SERVICES: '소비자 서비스',
  RETAILING: '임의소비재 유통 및 소매',
  FOOD_STAPLES_RETAILING: '필수소비재 유통 및 소매 ',
  FOOD_BEVERAGE_TOBACCO: '식품, 음료 및 담배',
  HOUSEHOLD_PERSONAL_PRODUCTS: '가정용품 및 개인용품',
  HEALTH_CARE_EQUIPMENT_SERVICES: '헬스케어 장비 및 서비스',
  PHARMACEUTICALS_BIOTECHNOLOGY_LIFE_SCIENCES: '제약, 생명공학 및 생명과학',
  BANKS: '은행',
  DIVERSIFIED_FINANCIALS: '금융 서비스',
  INSURANCE: '보험',
  SOFTWARE_SERVICES: '소프트웨어 및 서비스',
  TECHNOLOGY_HARDWARE_EQUIPMENT: '기술 하드웨어 및 장비',
  SEMICONDUCTORS_SEMICONDUCTOR_EQUIPMENT: '반도체 및 반도체 장비',
  TELECOMMUNICATION_SERVICES: '통신 서비스',
  MEDIA_ENTERTAINMENT: '미디어 및 엔터테인먼트',
  UTILITIES: '유틸리티',
  REAL_ESTATE: '주식리츠',
  REAL_ESTATE_MANAGEMENT_DEVELOPMENT: '부동산 관리 및 개발',
  UNCLASSIFIED: '미분류',
};
