# 테마 전략 상세
# 대가의 전략 상세
query getStrategy($id: ID!) {
  strategy(id: $id) {
    strategy {
      ... on ThemeStrategyType {
        ...ThemeStrategyTypeInfo
      }
      ... on MasterStrategyType {
        ...MasterStrategyTypeInfo
      }
      ... on SectorIndustryStrategyType {
        ...SectorIndustryStrategyTypeInfo
      }
    }
    errors {
      message
    }
  }
}
